ALL_ELEMENTS = [
    # ── BBN Elements (Hydrogen, Helium, Trace) ──
    {"z":1, "sym":"H",  "name":"Hydrogen",    "mass":1.008,  "cat":"BBN",      "color":"#88ccff", "fusion":None, "fuse_into": [{"el":"He","t_min":1e7,"fuel":4,"yield":0.993}], "n_source":None, "s_source":None, "r_source":None, "decay":None, "unlock":"", "abund":0.75},
    {"z":2, "sym":"He", "name":"Helium-4",    "mass":4.003,  "cat":"BBN",      "color":"#ffee88", "fusion":["H"], "fuse_into": [{"el":"C","t_min":1e8,"fuel":3,"yield":0.01},{"el":"Be","t_min":1e8,"fuel":3,"yield":0.0001}], "n_source":None, "s_source":None, "r_source":None, "decay":None, "unlock":"", "abund":0.24},
    {"z":3, "sym":"Li", "name":"Lithium-7",   "mass":6.941,  "cat":"BBN",      "color":"#cc44ff", "fusion":None, "fuse_into": [{"el":"Be","t_min":1e7,"fuel":2,"yield":0.01}], "n_source":None, "s_source":None, "r_source":None, "decay":None, "unlock":"", "abund":1e-9},
    {"z":4, "sym":"Be", "name":"Beryllium-9", "mass":9.012,  "cat":"BBN",      "color":"#aa22dd", "fusion":["He","Li"], "fuse_into":[{"el":"C","t_min":2e8,"fuel":2,"yield":0.5}], "n_source":None, "s_source":None, "r_source":None, "decay":None, "unlock":"", "abund":1e-10},
    {"z":5, "sym":"B",  "name":"Boron-11",    "mass":10.81,  "cat":"BBN",      "color":"#88dd88", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":None, "unlock":"", "abund":1e-8},
    {"z":6, "sym":"C",  "name":"Carbon-12",   "mass":12.011, "cat":"STELLAR",  "color":"#aaaaaa", "fusion":["He","Be"], "fuse_into":[{"el":"N","t_min":7e7,"fuel":2,"yield":0.4},{"el":"O","t_min":2e8,"fuel":2,"yield":0.3}], "n_source":"He+Be→C", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.005},
    {"z":7, "sym":"N",  "name":"Nitrogen-14",  "mass":14.007, "cat":"STELLAR",  "color":"#4488ff", "fusion":["C"], "fuse_into":[{"el":"O","t_min":5e7,"fuel":2,"yield":0.5}], "n_source":"C+O cycle", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.001},
    {"z":8, "sym":"O",  "name":"Oxygen-16",   "mass":15.999, "cat":"STELLAR",  "color":"#ff5555", "fusion":["C","N"], "fuse_into":[{"el":"Ne","t_min":2e8,"fuel":2,"yield":0.3}], "n_source":"C+He→O", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.008},
    {"z":9, "sym":"F",  "name":"Fluorine-19",  "mass":18.998, "cat":"STELLAR",  "color":"#88dd44", "fusion":None, "fuse_into":None, "n_source":"Neutrino spallation", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":4e-7},
    {"z":10,"sym":"Ne", "name":"Neon-20",     "mass":20.180, "cat":"STELLAR",  "color":"#ffaa44", "fusion":["O"], "fuse_into":[{"el":"Mg","t_min":1e9,"fuel":2,"yield":0.3}], "n_source":"O+He→Ne", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.002},
    {"z":11,"sym":"Na", "name":"Sodium-23",   "mass":22.990, "cat":"STELLAR",  "color":"#ffcc22", "fusion":None, "fuse_into":None, "n_source":"Ne burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":2e-5},
    {"z":12,"sym":"Mg", "name":"Magnesium-24","mass":24.305, "cat":"STELLAR",  "color":"#44ffaa", "fusion":["Ne"], "fuse_into":[{"el":"Si","t_min":1e9,"fuel":2,"yield":0.3}], "n_source":"Ne+He→Mg", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.0006},
    {"z":13,"sym":"Al", "name":"Aluminum-27", "mass":26.982, "cat":"STELLAR",  "color":"#bbbbcc", "fusion":None, "fuse_into":None, "n_source":"Mg burning, cosmic rays", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":5e-5},
    {"z":14,"sym":"Si", "name":"Silicon-28",  "mass":28.086, "cat":"STELLAR",  "color":"#ffcc44", "fusion":["Mg"], "fuse_into":[{"el":"S","t_min":2e9,"fuel":2,"yield":0.3}], "n_source":"Mg+He→Si", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.0007},
    {"z":15,"sym":"P",  "name":"Phosphorus-31","mass":30.974, "cat":"STELLAR",  "color":"#ff44aa", "fusion":None, "fuse_into":None, "n_source":"O+Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":3e-6},
    {"z":16,"sym":"S",  "name":"Sulfur-32",   "mass":32.065, "cat":"STELLAR",  "color":"#ffff44", "fusion":["Si"], "fuse_into":[{"el":"Ar","t_min":2e9,"fuel":2,"yield":0.2}], "n_source":"Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.0004},
    {"z":17,"sym":"Cl", "name":"Chlorine-35", "mass":35.453, "cat":"STELLAR",  "color":"#44ee44", "fusion":None, "fuse_into":None, "n_source":"O+Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":2e-6},
    {"z":18,"sym":"Ar", "name":"Argon-40",   "mass":39.948, "cat":"STELLAR",  "color":"#88ddee", "fusion":["S"], "fuse_into":[{"el":"Ca","t_min":3e9,"fuel":2,"yield":0.2}], "n_source":"Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.0001},
    {"z":19,"sym":"K",  "name":"Potassium-39","mass":39.098, "cat":"STELLAR",  "color":"#dd88ff", "fusion":None, "fuse_into":None, "n_source":"Si burning, O burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":3e-7},
    {"z":20,"sym":"Ca", "name":"Calcium-40",  "mass":40.078, "cat":"STELLAR",  "color":"#ff8844", "fusion":["Ar"], "fuse_into":[{"el":"Ti","t_min":3e9,"fuel":2,"yield":0.2}], "n_source":"Si burning chain", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":0.0006},
    {"z":21,"sym":"Sc", "name":"Scandium-45", "mass":44.956, "cat":"STELLAR",  "color":"#88aacc", "fusion":None, "fuse_into":None, "n_source":"Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":3e-8},
    {"z":22,"sym":"Ti", "name":"Titanium-48", "mass":47.867, "cat":"STELLAR",  "color":"#88aacc", "fusion":["Ca"], "fuse_into":[{"el":"Cr","t_min":3e9,"fuel":2,"yield":0.2}], "n_source":"Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":3e-5},
    {"z":23,"sym":"V",  "name":"Vanadium-51", "mass":50.942, "cat":"STELLAR",  "color":"#aacc88", "fusion":None, "fuse_into":None, "n_source":"Si burning", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":3e-7},
    {"z":24,"sym":"Cr", "name":"Chromium-52", "mass":51.996, "cat":"STELLAR",  "color":"#aa4444", "fusion":["Ti"], "fuse_into":[{"el":"Fe","t_min":4e9,"fuel":2,"yield":0.2}], "n_source":"Si burning endpoint", "s_source":None, "r_source":None, "decay":None, "unlock":"star", "abund":1e-5},
    {"z":25,"sym":"Mn", "name":"Manganese-55","mass":54.938, "cat":"SUPERNOVA","color":"#cc3344", "fusion":None, "fuse_into":None, "n_source":"Si burning, SN ejecta", "s_source":None, "r_source":None, "decay":None, "unlock":"supernova", "abund":3e-6},
    {"z":26,"sym":"Fe", "name":"Iron-56",    "mass":55.845, "cat":"SUPERNOVA","color":"#cc4422", "fusion":["Cr"], "fuse_into":None, "n_source":"Si burning(endpoint)", "s_source":None, "r_source":None, "decay":None, "unlock":"supernova", "abund":0.001},
    {"z":27,"sym":"Co", "name":"Cobalt-59",  "mass":58.933, "cat":"SUPERNOVA","color":"#4466cc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-6},
    {"z":28,"sym":"Ni", "name":"Nickel-58",  "mass":58.693, "cat":"SUPERNOVA","color":"#aa6633", "fusion":None, "fuse_into":None, "n_source":"Si burning, SN", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-5},
    {"z":29,"sym":"Cu", "name":"Copper-63",  "mass":63.546, "cat":"SUPERNOVA","color":"#dd7722", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-7},
    {"z":30,"sym":"Zn", "name":"Zinc-64",    "mass":65.38,  "cat":"SUPERNOVA","color":"#88bb99", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":6e-7},
    {"z":31,"sym":"Ga", "name":"Gallium-69", "mass":69.723, "cat":"SUPERNOVA","color":"#cc99aa", "fusion":None, "fuse_into":None, "n_source":"SN/AGB", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-7},
    {"z":32,"sym":"Ge", "name":"Germanium-74","mass":72.64, "cat":"SUPERNOVA","color":"#8899aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-7},
    {"z":33,"sym":"As", "name":"Arsenic-75", "mass":74.922, "cat":"SUPERNOVA","color":"#aa88cc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":34,"sym":"Se", "name":"Selenium-80","mass":78.96,  "cat":"SUPERNOVA","color":"#66aa44", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-7},
    {"z":35,"sym":"Br", "name":"Bromine-79", "mass":79.904, "cat":"SUPERNOVA","color":"#aa2244", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":36,"sym":"Kr", "name":"Krypton-84", "mass":83.798, "cat":"SUPERNOVA","color":"#88dddd", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":37,"sym":"Rb", "name":"Rubidium-85","mass":85.468, "cat":"SUPERNOVA","color":"#cc6688", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":38,"sym":"Sr", "name":"Strontium-88","mass":87.62, "cat":"SUPERNOVA","color":"#88cc66", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-7},
    {"z":39,"sym":"Y",  "name":"Yttrium-89", "mass":88.906, "cat":"SUPERNOVA","color":"#99bbcc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-8},
    {"z":40,"sym":"Zr", "name":"Zirconium-90","mass":91.224, "cat":"SUPERNOVA","color":"#aaaa88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-7},
    {"z":41,"sym":"Nb", "name":"Niobium-93", "mass":92.906, "cat":"SUPERNOVA","color":"#ccaa88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":42,"sym":"Mo", "name":"Molybdenum-96","mass":95.96, "cat":"SUPERNOVA","color":"#889988", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-7},
    {"z":43,"sym":"Tc", "name":"Technetium-98","mass":98.0,  "cat":"SUPERNOVA","color":"#448888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process", "decay":{"to":"Ru","hl":2.13e5}, "unlock":"supernova", "abund":0},
    {"z":44,"sym":"Ru", "name":"Ruthenium-102","mass":101.07,"cat":"SUPERNOVA","color":"#8899aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-7},
    {"z":45,"sym":"Rh", "name":"Rhodium-103","mass":102.91, "cat":"SUPERNOVA","color":"#cccc99", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":46,"sym":"Pd", "name":"Palladium-106","mass":106.42,"cat":"SUPERNOVA","color":"#99bbaa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-7},
    {"z":47,"sym":"Ag", "name":"Silver-107", "mass":107.87, "cat":"SUPERNOVA","color":"#dddddd", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":48,"sym":"Cd", "name":"Cadmium-114","mass":112.41, "cat":"SUPERNOVA","color":"#aa9988", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":49,"sym":"In", "name":"Indium-115", "mass":114.82, "cat":"SUPERNOVA","color":"#bb88cc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":50,"sym":"Sn", "name":"Tin-120",    "mass":118.71, "cat":"SUPERNOVA","color":"#aaaaaa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-7},
    {"z":51,"sym":"Sb", "name":"Antimony-121","mass":121.76, "cat":"SUPERNOVA","color":"#aaaa88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":52,"sym":"Te", "name":"Tellurium-128","mass":127.60,"cat":"SUPERNOVA","color":"#88aa66", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":53,"sym":"I",  "name":"Iodine-127", "mass":126.90, "cat":"SUPERNOVA","color":"#8844aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":4e-9},
    {"z":54,"sym":"Xe", "name":"Xenon-132",  "mass":131.29, "cat":"SUPERNOVA","color":"#88ffcc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-9},
    {"z":55,"sym":"Cs", "name":"Cesium-133", "mass":132.91, "cat":"SUPERNOVA","color":"#aa8844", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":56,"sym":"Ba", "name":"Barium-138", "mass":137.33, "cat":"SUPERNOVA","color":"#ee8833", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-7},
    {"z":57,"sym":"La", "name":"Lanthanum-139","mass":138.91,"cat":"SUPERNOVA","color":"#aabb88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":58,"sym":"Ce", "name":"Cerium-140", "mass":140.12, "cat":"SUPERNOVA","color":"#bbaa88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":59,"sym":"Pr", "name":"Praseodymium-141","mass":140.91,"cat":"SUPERNOVA","color":"#88bb88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":60,"sym":"Nd", "name":"Neodymium-144","mass":144.24,"cat":"SUPERNOVA","color":"#aa88aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":61,"sym":"Pm", "name":"Promethium-145","mass":145.0, "cat":"SUPERNOVA","color":"#886688", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":{"to":"Nd","hl":17.7*365*86400}, "unlock":"supernova", "abund":0},
    {"z":62,"sym":"Sm", "name":"Samarium-152","mass":150.36,"cat":"SUPERNOVA","color":"#99aa88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":63,"sym":"Eu", "name":"Europium-153","mass":151.96,"cat":"SUPERNOVA","color":"#aa88cc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-9},
    {"z":64,"sym":"Gd", "name":"Gadolinium-158","mass":157.25,"cat":"SUPERNOVA","color":"#99aaaa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-8},
    {"z":65,"sym":"Tb", "name":"Terbium-159","mass":158.93,"cat":"SUPERNOVA","color":"#88aa99", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-9},
    {"z":66,"sym":"Dy", "name":"Dysprosium-164","mass":162.50,"cat":"SUPERNOVA","color":"#88bbaa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-8},
    {"z":67,"sym":"Ho", "name":"Holmium-165","mass":164.93,"cat":"SUPERNOVA","color":"#aa88aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":68,"sym":"Er", "name":"Erbium-166","mass":167.26,"cat":"SUPERNOVA","color":"#99bb88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":69,"sym":"Tm", "name":"Thulium-169","mass":168.93,"cat":"SUPERNOVA","color":"#88aacc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":None, "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-9},
    {"z":70,"sym":"Yb", "name":"Ytterbium-174","mass":173.04,"cat":"SUPERNOVA","color":"#99aaaa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":71,"sym":"Lu", "name":"Lutetium-175","mass":174.97,"cat":"SUPERNOVA","color":"#88aa99", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-9},
    {"z":72,"sym":"Hf", "name":"Hafnium-180","mass":178.49,"cat":"SUPERNOVA","color":"#8899aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":73,"sym":"Ta", "name":"Tantalum-181","mass":180.95,"cat":"SUPERNOVA","color":"#99aabb", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":74,"sym":"W",  "name":"Tungsten-184","mass":183.84,"cat":"SUPERNOVA","color":"#99bbcc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-7},
    {"z":75,"sym":"Re", "name":"Rhenium-187","mass":186.21,"cat":"SUPERNOVA","color":"#aabb88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":76,"sym":"Os", "name":"Osmium-192","mass":190.23,"cat":"SUPERNOVA","color":"#9999aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":77,"sym":"Ir", "name":"Iridium-193","mass":192.22,"cat":"SUPERNOVA","color":"#aabbdd", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":78,"sym":"Pt", "name":"Platinum-195","mass":195.08,"cat":"SUPERNOVA","color":"#cccccc", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-8},
    {"z":79,"sym":"Au", "name":"Gold-197",  "mass":196.97,"cat":"SUPERNOVA","color":"#ffd700", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-9},
    {"z":80,"sym":"Hg", "name":"Mercury-202","mass":200.59,"cat":"SUPERNOVA","color":"#aa88aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":81,"sym":"Tl", "name":"Thallium-205","mass":204.38,"cat":"SUPERNOVA","color":"#aabb88", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":82,"sym":"Pb", "name":"Lead-208",   "mass":207.2, "cat":"SUPERNOVA","color":"#888899", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process(end)", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":2e-8},
    {"z":83,"sym":"Bi", "name":"Bismuth-209","mass":208.98,"cat":"SUPERNOVA","color":"#aa99aa", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":5e-9},
    {"z":84,"sym":"Po", "name":"Polonium-209","mass":209.0, "cat":"SUPERNOVA","color":"#8866aa", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process", "decay":{"to":"Pb","hl":102*365*86400}, "unlock":"supernova", "abund":0},
    {"z":85,"sym":"At", "name":"Astatine-210","mass":210.0, "cat":"SUPERNOVA","color":"#664488", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process", "decay":{"to":"Bi","hl":8.1*3600}, "unlock":"supernova", "abund":0},
    {"z":86,"sym":"Rn", "name":"Radon-222",  "mass":222.0, "cat":"SUPERNOVA","color":"#88aacc", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Po","hl":3.82*86400}, "unlock":"supernova", "abund":0},
    {"z":87,"sym":"Fr", "name":"Francium-223","mass":223.0, "cat":"SUPERNOVA","color":"#aa6688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Ra","hl":22*60}, "unlock":"supernova", "abund":0},
    {"z":88,"sym":"Ra", "name":"Radium-226", "mass":226.03,"cat":"SUPERNOVA","color":"#88aa66", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process", "decay":{"to":"Rn","hl":1600*365*86400}, "unlock":"supernova", "abund":0},

    # ── Th-U series (r-process in SN) ──
    {"z":90,"sym":"Th", "name":"Thorium-232","mass":232.04,"cat":"SUPERNOVA","color":"#44aa44", "fusion":None, "fuse_into":None, "n_source":None, "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":3e-8},
    {"z":91,"sym":"Pa", "name":"Protactinium-231","mass":231.04,"cat":"SUPERNOVA","color":"#44aa88", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process", "decay":{"to":"Ac","hl":32760*365*86400}, "unlock":"supernova", "abund":0},
    {"z":92,"sym":"U",  "name":"Uranium-238","mass":238.03,"cat":"SUPERNOVA","color":"#22ff44", "fusion":None, "fuse_into":None, "n_source":"SN r-process", "s_source":"AGB s-process", "r_source":"SN r-process", "decay":None, "unlock":"supernova", "abund":1e-8},
    {"z":93,"sym":"Np", "name":"Neptunium-237","mass":237.0, "cat":"SYNTHETIC","color":"#44dd88", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"U","hl":2.14e6*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":94,"sym":"Pu", "name":"Plutonium-244","mass":244.0, "cat":"SYNTHETIC","color":"#aa44aa", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":"SN r-process(trace)", "decay":None, "unlock":"synthetic", "abund":0},
    {"z":95,"sym":"Am", "name":"Americium-243","mass":243.0, "cat":"SYNTHETIC","color":"#88aa66", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Np","hl":7370*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":96,"sym":"Cm", "name":"Curium-247","mass":247.0, "cat":"SYNTHETIC","color":"#669988", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Pu","hl":1.56e7*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":97,"sym":"Bk", "name":"Berkelium-247","mass":247.0, "cat":"SYNTHETIC","color":"#886688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Cm","hl":1380*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":98,"sym":"Cf", "name":"Californium-251","mass":251.0, "cat":"SYNTHETIC","color":"#6688aa", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Cm","hl":898*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":99,"sym":"Es", "name":"Einsteinium-252","mass":252.0, "cat":"SYNTHETIC","color":"#886666", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Bk","hl":472*365*86400}, "unlock":"synthetic", "abund":0},
    {"z":100,"sym":"Fm","name":"Fermium-257","mass":257.0, "cat":"SYNTHETIC","color":"#668888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Cf","hl":100.5*86400}, "unlock":"synthetic", "abund":0},
    {"z":101,"sym":"Md","name":"Mendelevium-258","mass":258.0,"cat":"SYNTHETIC","color":"#886688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Es","hl":51.5*86400}, "unlock":"synthetic", "abund":0},
    {"z":102,"sym":"No","name":"Nobelium-259","mass":259.0, "cat":"SYNTHETIC","color":"#668866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Fm","hl":58*60}, "unlock":"synthetic", "abund":0},
    {"z":103,"sym":"Lr","name":"Lawrencium-262","mass":262.0, "cat":"SYNTHETIC","color":"#886666", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Md","hl":3.6*3600}, "unlock":"synthetic", "abund":0},
    {"z":104,"sym":"Rf","name":"Rutherfordium-267","mass":267.0,"cat":"SYNTHETIC","color":"#888866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"No","hl":1.3*3600}, "unlock":"synthetic", "abund":0},
    {"z":105,"sym":"Db","name":"Dubnium-268","mass":268.0, "cat":"SYNTHETIC","color":"#668888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Lr","hl":29*3600}, "unlock":"synthetic", "abund":0},
    {"z":106,"sym":"Sg","name":"Seaborgium-269","mass":269.0,"cat":"SYNTHETIC","color":"#888866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Rf","hl":14*60}, "unlock":"synthetic", "abund":0},
    {"z":107,"sym":"Bh","name":"Bohrium-270","mass":270.0, "cat":"SYNTHETIC","color":"#886688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Db","hl":61*60}, "unlock":"synthetic", "abund":0},
    {"z":108,"sym":"Hs","name":"Hassium-270","mass":270.0, "cat":"SYNTHETIC","color":"#888866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Sg","hl":7.6*60}, "unlock":"synthetic", "abund":0},
    {"z":109,"sym":"Mt","name":"Meitnerium-278","mass":278.0,"cat":"SYNTHETIC","color":"#666688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Bh","hl":7.6*60}, "unlock":"synthetic", "abund":0},
    {"z":110,"sym":"Ds","name":"Darmstadtium-281","mass":281.0,"cat":"SYNTHETIC","color":"#888888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Hs","hl":11*60}, "unlock":"synthetic", "abund":0},
    {"z":111,"sym":"Rg","name":"Roentgenium-282","mass":282.0,"cat":"SYNTHETIC","color":"#888688", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Mt","hl":100*60}, "unlock":"synthetic", "abund":0},
    {"z":112,"sym":"Cn","name":"Copernicium-285","mass":285.0,"cat":"SYNTHETIC","color":"#888866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Ds","hl":30*60}, "unlock":"synthetic", "abund":0},
    {"z":113,"sym":"Nh","name":"Nihonium-286","mass":286.0, "cat":"SYNTHETIC","color":"#868888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Rg","hl":9.5*60}, "unlock":"synthetic", "abund":0},
    {"z":114,"sym":"Fl","name":"Flerovium-289","mass":289.0, "cat":"SYNTHETIC","color":"#888866", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Cn","hl":2.6*60}, "unlock":"synthetic", "abund":0},
    {"z":115,"sym":"Mc","name":"Moscovium-290","mass":290.0, "cat":"SYNTHETIC","color":"#868888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Nh","hl":0.65*60}, "unlock":"synthetic", "abund":0},
    {"z":116,"sym":"Lv","name":"Livermorium-293","mass":293.0,"cat":"SYNTHETIC","color":"#888888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Fl","hl":57*60}, "unlock":"synthetic", "abund":0},
    {"z":117,"sym":"Ts","name":"Tennessine-294","mass":294.0, "cat":"SYNTHETIC","color":"#888888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Mc","hl":51*60}, "unlock":"synthetic", "abund":0},
    {"z":118,"sym":"Og","name":"Oganesson-294","mass":294.0, "cat":"SYNTHETIC","color":"#888888", "fusion":None, "fuse_into":None, "n_source":None, "s_source":None, "r_source":None, "decay":{"to":"Lv","hl":0.69*60}, "unlock":"synthetic", "abund":0},
]

# Add Fr, Ac, Pa which were omitted (they exist as decay intermediates)
# z=87 Fr already above, z=89 Ac:
AC = {"z":89,"sym":"Ac","name":"Actinium-227","mass":227.0,"cat":"SUPERNOVA","color":"#66aa88","fusion":None,"fuse_into":None,"n_source":None,"s_source":None,"r_source":"SN r-process","decay":{"to":"Th","hl":21.77*365*86400},"unlock":"supernova","abund":0}
ALL_ELEMENTS.append(AC)

ELEM_MAP = {e["sym"]: e for e in ALL_ELEMENTS}

def get_elem(sym):
    return ELEM_MAP.get(sym)

def elem_color(sym):
    e = get_elem(sym)
    return e["color"] if e else "#ffffff"

def elem_fusion(sym):
    e = get_elem(sym)
    return e.get("fuse_into")

def elem_decay(sym):
    e = get_elem(sym)
    return e.get("decay")

def is_synthetic(sym):
    e = get_elem(sym)
    return e and e["cat"] == "SYNTHETIC"
