export const ELEMENTS=[
  {sym:'H',  name:'Hydrogen',    phase:'BBN',      color:'#88ccff',unlock:true, desc:'Most abundant. Fuel for stars.'},
  {sym:'²H', name:'Deuterium',   phase:'BBN',      color:'#66aaff',unlock:true, desc:'Heavy Hydrogen isotope.'},
  {sym:'He', name:'Helium-4',    phase:'BBN',      color:'#ffee88',unlock:true, desc:'Stellar fusion byproduct.'},
  {sym:'³He',name:'Helium-3',    phase:'BBN',      color:'#ffdd66',unlock:true, desc:'Trace Helium isotope.'},
  {sym:'Li', name:'Lithium-7',   phase:'BBN',      color:'#33ff77',unlock:true, desc:'Trace BBN alkali metal.'},
  {sym:'Be', name:'Beryllium-7', phase:'BBN',      color:'#ff55aa',unlock:true, desc:'Trace BBN product.'},
  {sym:'C',  name:'Carbon-12',   phase:'STELLAR',  color:'#aaaaaa',unlock:false,desc:'Backbone of organic life.'},
  {sym:'N',  name:'Nitrogen-14', phase:'STELLAR',  color:'#4488ff',unlock:false,desc:'CNO cycle product.'},
  {sym:'O',  name:'Oxygen-16',   phase:'STELLAR',  color:'#ff5555',unlock:false,desc:'Essential for water & respiration.'},
  {sym:'Ne', name:'Neon-20',     phase:'STELLAR',  color:'#ffaa44',unlock:false,desc:'Noble gas from C burning.'},
  {sym:'Mg', name:'Magnesium',   phase:'STELLAR',  color:'#44ffaa',unlock:false,desc:'Neon burning phase.'},
  {sym:'Si', name:'Silicon-28',  phase:'STELLAR',  color:'#ffcc44',unlock:false,desc:'Rocky planet core builder.'},
  {sym:'S',  name:'Sulfur-32',   phase:'STELLAR',  color:'#ffff44',unlock:false,desc:'Silicon burning product.'},
  {sym:'Ca', name:'Calcium-40',  phase:'STELLAR',  color:'#ff8844',unlock:false,desc:'Stellar nucleosynthesis.'},
  {sym:'Na', name:'Sodium-23',   phase:'STELLAR',  color:'#ffcc22',unlock:false,desc:'Ne burning product.'},
  {sym:'Al', name:'Aluminum-27', phase:'STELLAR',  color:'#bbbbcc',unlock:false,desc:'Mg burning product.'},
  {sym:'Ti', name:'Titanium-48', phase:'STELLAR',  color:'#88aacc',unlock:false,desc:'Advanced fusion.'},
  {sym:'Cr', name:'Chromium-52', phase:'STELLAR',  color:'#aa4444',unlock:false,desc:'Si burning endpoint.'},
  {sym:'Fe', name:'Iron-56',     phase:'SUPERNOVA',color:'#cc4422',unlock:false,desc:'Most stable nucleus.'},
  {sym:'Ni', name:'Nickel-56',   phase:'SUPERNOVA',color:'#aa6633',unlock:false,desc:'Decays to Fe in supernova.'},
  {sym:'Co', name:'Cobalt-59',   phase:'SUPERNOVA',color:'#4466cc',unlock:false,desc:'r-process product.'},
  {sym:'Cu', name:'Copper-63',   phase:'SUPERNOVA',color:'#dd7722',unlock:false,desc:'r-process product.'},
  {sym:'Zn', name:'Zinc-64',     phase:'SUPERNOVA',color:'#88bb99',unlock:false,desc:'r-process product.'},
  {sym:'Ag', name:'Silver-107',  phase:'SUPERNOVA',color:'#dddddd',unlock:false,desc:'Precious metal.'},
  {sym:'Au', name:'Gold-197',    phase:'SUPERNOVA',color:'#ffd700',unlock:false,desc:'Neutron star merger product.'},
  {sym:'Pb', name:'Lead-208',    phase:'SUPERNOVA',color:'#888899',unlock:false,desc:'Heavy s-process end.'},
  {sym:'Pt', name:'Platinum',    phase:'SUPERNOVA',color:'#cccccc',unlock:false,desc:'r-process metal.'},
  {sym:'U',  name:'Uranium-238', phase:'SUPERNOVA',color:'#22ff44',unlock:false,desc:'Radioactive r-process.'},
  {sym:'Mn', name:'Manganese',   phase:'SUPERNOVA',color:'#cc3344',unlock:false,desc:'Supernova ejecta.'},
  {sym:'Ba', name:'Barium-138',  phase:'SUPERNOVA',color:'#ee8833',unlock:false,desc:'AGB star s-process.'},
  {sym:'W',  name:'Tungsten',    phase:'SUPERNOVA',color:'#99bbcc',unlock:false,desc:'Refractory metal.'},
  {sym:'Ir', name:'Iridium',     phase:'SUPERNOVA',color:'#aabbdd',unlock:false,desc:'Dense cosmic element.'},
  {sym:'Xe', name:'Xenon-131',   phase:'SUPERNOVA',color:'#88ffcc',unlock:false,desc:'Heavy noble gas.'},
];
